name: macOS Build (arm64)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure (CMake)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_ARCHITECTURES=arm64

      - name: Build
        run: cmake --build build --config RelWithDebInfo --parallel

      - name: Pack artifacts
        run: |
          mkdir -p dist
          cp -R build/*.mxo dist/ || true
          cp -R build/bin/* dist/ 2>/dev/null || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-artifacts
          path: dist
